[project]
name = 'stacks-xox-game'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.stacks-xox-game]
path = 'contracts/xox-game.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
